# Form implementation generated from reading ui file 'C:\Users\Admin\PycharmProjects\PythonProject1\Managementcinema\file ui\dangky.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from register_handler import register, create_db,suggest_username  # Import file xử lý đăng ký
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        images_folder = os.path.join(project_root, "images")
        image_path = os.path.join(images_folder, "dangky.png")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(488, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_dangki = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_dangki.setGeometry(QtCore.QRect(200, 500, 111, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_dangki.setFont(font)
        self.pushButton_dangki.setStyleSheet("background-color: rgb(181, 62, 138);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px\n"
"")
        self.pushButton_dangki.setObjectName("pushButton_dangki")
        self.lineEdit_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(80, 110, 331, 31))
        self.lineEdit_email.setStyleSheet("\n"
"background-color: rgb(248, 255, 168);\n"
"border:3px;\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_dnhap = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_dnhap.setGeometry(QtCore.QRect(80, 190, 331, 31))
        self.lineEdit_dnhap.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(248, 255, 168);\n"
"border:3px;\n"
"")
        self.lineEdit_dnhap.setObjectName("lineEdit_dnhap")
        self.lineEdit_dthoai = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_dthoai.setGeometry(QtCore.QRect(90, 270, 331, 31))
        self.lineEdit_dthoai.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(248, 255, 168);\n"
"border:3px;\n"
"")
        self.lineEdit_dthoai.setObjectName("lineEdit_dthoai")
        self.lineEdit_mkhau = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_mkhau.setGeometry(QtCore.QRect(90, 350, 331, 31))
        self.lineEdit_mkhau.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(248, 255, 168);\n"
"border:3px;\n"
"")
        self.lineEdit_mkhau.setObjectName("lineEdit_mkhau")
        self.lineEdit_nhaplaimk = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_nhaplaimk.setGeometry(QtCore.QRect(90, 430, 331, 31))
        self.lineEdit_nhaplaimk.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(248, 255, 168);\n"
"border:3px;\n"
"")
        self.lineEdit_nhaplaimk.setObjectName("lineEdit_nhaplaimk")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -15, 501, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(images_folder,"dangky.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButton_dangki.raise_()
        self.lineEdit_email.raise_()
        self.lineEdit_dnhap.raise_()
        self.lineEdit_dthoai.raise_()
        self.lineEdit_mkhau.raise_()
        self.lineEdit_nhaplaimk.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.lineEdit_email.textChanged.connect(lambda: suggest_username(self))
        self.pushButton_dangki.clicked.connect(self.handle_register)
        self.lineEdit_nhaplaimk.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_dangki.setText(_translate("MainWindow", "Signup"))

    def handle_register(self):
            username = self.lineEdit_dnhap.text()
            email = self.lineEdit_email.text()
            phone = self.lineEdit_dthoai.text()
            password = self.lineEdit_mkhau.text()
            confirm_password = self.lineEdit_nhaplaimk.text()

            register(username, email, phone, password, confirm_password, self.centralwidget)

if __name__ == "__main__":
    import sys
    create_db
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())