# Form implementation generated from reading ui file 'C:\Users\Admin\PycharmProjects\PythonProject1\Quản lý vé xem phim\file ui\dangnhapadmin.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os
from PyQt6 import QtCore, QtGui, QtWidgets
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Thêm thư mục gốc vào sys.path
sys.path.append(project_root)

from Managementwindow.MainWindow import Ui_MainWindow as ManagementUI

from register_handler import kiemtraadmin, kiemtra_trong_db

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Lấy thư mục gốc "Quản lý vé xem phim"
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        images_folder = os.path.join(project_root, "images")
        image_path = os.path.join(images_folder, "loginadmin.png")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 501)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -15, 821, 491))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(images_folder,"loginadmin.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.matkhauadmin = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.matkhauadmin.setGeometry(QtCore.QRect(80, 280, 271, 41))
        self.matkhauadmin.setStyleSheet("background-color: rgb(248, 255, 168);\n"
"border: 3px;\n"
"color: rgb(0, 0, 0);")
        self.matkhauadmin.setObjectName("matkhauadmin")
        self.dangnhapadmin = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.dangnhapadmin.setGeometry(QtCore.QRect(80, 160, 271, 51))
        self.dangnhapadmin.setStyleSheet("background-color: rgb(248, 255, 168);\n"
"border: 3px;\n"
"color: rgb(0, 0, 0);")
        self.dangnhapadmin.setObjectName("dangnhapadmin")
        self.loginadmin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loginadmin.setGeometry(QtCore.QRect(160, 380, 111, 41))
        self.loginadmin.setStyleSheet("background-color: rgb(181, 62, 138);\n"
"border: 3px;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"8514oem\";")
        self.loginadmin.setObjectName("loginadmin")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-6, -5, 811, 481))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\Admin\\PycharmProjects\\PythonProject1\\Quản lý vé xem phim\\file ui\\../../../../Downloads/loginadmin.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(690, 420, 61, 21))
        self.back.setStyleSheet("background-color: rgb(181, 62, 138);\n"
"border: 3px;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"8514oem\";")
        self.back.setObjectName("back")
        self.label_2.raise_()
        self.label.raise_()
        self.matkhauadmin.raise_()
        self.dangnhapadmin.raise_()
        self.loginadmin.raise_()
        self.back.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.loginadmin.clicked.connect(self.login_admin)
        self.matkhauadmin.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.MainWindow = MainWindow
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginadmin.setText(_translate("MainWindow", "Login"))
        self.back.setText(_translate("MainWindow", "Back"))
    def login_admin(self):
        print("Bắt đầu kiểm tra đăng nhập...")  # Kiểm tra xem có chạy vào hàm không
        username = self.dangnhapadmin.text()
        password = self.matkhauadmin.text()
        print(f"Username: {username}, Password: {password}")
        try:
            if kiemtraadmin(username, password):
                print("Đăng nhập thành công, chuẩn bị mở cửa sổ quản lý...")
                self.open_quanlylon()
                return
            if kiemtra_trong_db(username, password):
                print("Đăng nhập thành công! Mở cửa sổ chức năng...")
                self.open_management()
                return
            print("Sai tài khoản hoặc mật khẩu!")
            QtWidgets.QMessageBox.warning(self, "Lỗi", "Sai tài khoản hoặc mật khẩu!")
        except Exception as e:
            print(f"🚨 Lỗi khi kiểm tra đăng nhập: {e}")

    def open_management(self):
        print("Mở cửa sổ quản lý...")  # Kiểm tra xem hàm có chạy không
        self.management_window = QtWidgets.QMainWindow()
        self.ui = ManagementUI()
        self.ui.setupUi(self.management_window)
        self.management_window.show()
        print("Đã hiển thị cửa sổ quản lý!")  # Kiểm tra nếu cửa sổ được hiển thị
        self.MainWindow.close()
    def open_quanlylon(self):
        """Mở cửa sổ chức năng (window 2)"""
        from quanlygiaodien import MainWindow as QuanlyUi
        print("Mở cửa sổ chức năng...")
        self.function_window = QuanlyUi()
        self.function_window.show()
        self.MainWindow.close()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())