# Form implementation generated from reading ui file 'C:\Users\DELL\baithuchanh\Chức năng quản lý\giaodienmodau.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os
import sys
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Thêm thư mục gốc vào sys.path
sys.path.append(project_root)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
            # Lấy thư mục gốc "Quản lý vé xem phim"
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        images_folder = os.path.join(project_root, "images")
        image_path = os.path.join(images_folder, "hinhdau.png")
            # Load hình ảnh từ thư mục images
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 425)
        font = QtGui.QFont()
        font.setPointSize(18)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                    stop:0 #FFF7AD, \n"
"                    stop:0.5 #FFA9F9, \n"
"                    stop:1 #D98BBF);\n"
"    }\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                    stop:0 #FFF7AD, \n"
"                    stop:0.5 #FFA9F9, \n"
"                    stop:1 #D98BBF);\n"
"    }\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonDangxuat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonDangxuat.setGeometry(QtCore.QRect(450, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonDangxuat.setFont(font)
        self.ButtonDangxuat.setStyleSheet(" QPushButton {\n"
"        background-color: rgb(181, 62, 138);\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        border-radius: 10px;\n"
"        padding: 5px 10px;\n"
"        border: 2px solid #4682B4;\n"
"    }")
        self.ButtonDangxuat.setObjectName("ButtonDangxuat")
        self.groupInfoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.groupInfoLabel.setGeometry(QtCore.QRect(-20, 50, 600, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        self.groupInfoLabel.setFont(font)
        self.groupInfoLabel.setStyleSheet("background-color:transparent")
        self.groupInfoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupInfoLabel.setObjectName("groupInfoLabel")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 140, 311, 231))
        self.label.setStyleSheet("background-color:transparent")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(images_folder,"hinhdau.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.ButtonDoanhthu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonDoanhthu.setGeometry(QtCore.QRect(50, 230, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonDoanhthu.setFont(font)
        self.ButtonDoanhthu.setStyleSheet(" QPushButton {\n"
"        background-color: rgb(181, 62, 138);\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        border-radius: 10px;\n"
"        padding: 5px 10px;\n"
"        border: 2px solid #4682B4;\n"
"    }")
        self.ButtonDoanhthu.setObjectName("ButtonDoanhthu")
        self.ButtonNhanVien = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonNhanVien.setGeometry(QtCore.QRect(50, 160, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonNhanVien.setFont(font)
        self.ButtonNhanVien.setStyleSheet(" QPushButton {\n"
"        background-color: rgb(181, 62, 138);\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        border-radius: 10px;\n"
"        padding: 5px 10px;\n"
"        border: 2px solid #4682B4;\n"
"    }")
        self.ButtonNhanVien.setObjectName("ButtonNhanVien")
        self.ButtonChung = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonChung.setGeometry(QtCore.QRect(50, 300, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonChung.setFont(font)
        self.ButtonChung.setStyleSheet(" QPushButton {\n"
"        background-color: rgb(181, 62, 138);\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        border-radius: 10px;\n"
"        padding: 5px 10px;\n"
"        border: 2px solid #4682B4;\n"
"    }")
        self.ButtonChung.setObjectName("ButtonChung")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Admin"))
        self.ButtonDangxuat.setText(_translate("MainWindow", "Đăng xuất"))
        self.groupInfoLabel.setText(_translate("MainWindow", "KTLT\'s Cinema - K24416\n"
"Movie Ticket Management System"))
        self.ButtonDoanhthu.setText(_translate("MainWindow", "Báo cáo doanh thu"))
        self.ButtonNhanVien.setText(_translate("MainWindow", "Quản lý nhân viên"))
        self.ButtonChung.setText(_translate("MainWindow", "Quản lý chung"))
