# Form implementation generated from reading ui file 'C:\Users\Admin\PycharmProjects\PythonProject1\Quản lý vé xem phim\file ui\dangnhap.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "Bookticket")))
from PyQt6 import QtCore, QtGui, QtWidgets
from register_handler import check_login
from main import MainApp


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Lấy thư mục gốc "Quản lý vé xem phim"
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        images_folder = os.path.join(project_root, "images")
        image_path = os.path.join(images_folder, "dangnhapusers.png")
        print("Đường dẫn ảnh:", image_path)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 413)
        MainWindow.setStyleSheet("background-color: rgb(237, 155, 222);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username.setGeometry(QtCore.QRect(60, 130, 251, 31))
        self.username.setStyleSheet("background-color: rgb(248, 255, 168);\n"
"color: rgb(0, 0, 0);\n"
"border: 3px")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(50, 240, 251, 31))
        self.password.setStyleSheet("background-color: rgb(248, 255, 168);\n"
"border: 3px;\n"
"color: rgb(0, 0, 0);")
        self.password.setObjectName("password")
        self.dangnhap = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dangnhap.setGeometry(QtCore.QRect(50, 310, 91, 28))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dangnhap.setFont(font)
        self.dangnhap.setStyleSheet("background-color: rgb(181, 62, 138);\n"
"border: 3px;\n"
"color: rgb(255, 255, 255);")
        self.dangnhap.setObjectName("dangnhap")
        self.dangky = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dangky.setGeometry(QtCore.QRect(200, 310, 91, 28))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dangky.setFont(font)
        self.dangky.setStyleSheet("background-color: rgb(181, 62, 138);\n"
"border: 3px;\n"
"color: rgb(255, 255, 255);")
        self.dangky.setObjectName("dangky")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, -10, 671, 411))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(os.path.join(images_folder,"dangnhapusers.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(570, 350, 51, 21))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: rgb(181, 62, 138);\n"
"border: 3px;\n"
"color: rgb(255, 255, 255);")
        self.back.setObjectName("back")
        self.label_2.raise_()
        self.username.raise_()
        self.password.raise_()
        self.dangnhap.raise_()
        self.dangky.raise_()
        self.back.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.dangnhap.clicked.connect(self.handle_login)
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.MainWindow = MainWindow

    def handle_login(self):
        username = self.username.text()
        password = self.password.text()

        if check_login(username, password):
            print(' chuẩn bị vô hàm')
            self.open_main_app()
        else:
            QtWidgets.QMessageBox.warning(None, "Lỗi", "Sai tài khoản hoặc mật khẩu!")

    def open_main_app(self):
        print(' thực thi')
        self.MainWindow.hide()  # Ẩn cửa sổ đăng nhập
        self.main_window = MainApp()
        self.main_window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dangnhap.setText(_translate("MainWindow", "Login"))
        self.dangky.setText(_translate("MainWindow", "Signup"))
        self.back.setText(_translate("MainWindow", "Back"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())