# Form implementation generated from reading ui file 'C:\Users\Admin\PycharmProjects\PythonProject1\Quản lý vé xem phim\mainwd.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Lấy thư mục gốc "Quản lý vé xem phim"
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        images_folder = os.path.join(project_root, "images")
        image_path = os.path.join(images_folder, "Ung dung quan ly & ban ve xem phim.png")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"background-color:rgb(227, 124, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 801, 571))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(images_folder,"Ung dung quan ly & ban ve xem phim.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Users = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Users.setGeometry(QtCore.QRect(470, 340, 111, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Users.setFont(font)
        self.Users.setStyleSheet("background-color: rgb(181, 62, 138);\n"
"border: 3px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Users.setObjectName("Users")
        self.Admin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Admin.setGeometry(QtCore.QRect(210, 340, 111, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Admin.setFont(font)
        self.Admin.setStyleSheet("background-color: rgb(181, 62, 138);\n"
"border: 3px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Admin.setObjectName("Admin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Users.setText(_translate("MainWindow", "USERS"))
        self.Admin.setText(_translate("MainWindow", "ADMIN"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())