# Form implementation generated from reading ui file 'C:\Users\Admin\PycharmProjects\PythonProject1\Quản lý vé xem phim\file ui\giaodienchucnangdoanhthu.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

class Ui_RevenueWindow(object):
    def setupUi(self, MainWindow):
            # Lấy thư mục gốc "Quản lý vé xem phim"
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        images_folder = os.path.join(project_root, "images")
        image_path = os.path.join(images_folder, "nen.png")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 596)
        MainWindow.setStyleSheet(" QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                    stop:0 #FFF7AD, \n"
"                    stop:0.5 #FFA9F9, \n"
"                    stop:1 #D98BBF);\n"
"    }\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonXoaDT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonXoaDT.setGeometry(QtCore.QRect(390, 460, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonXoaDT.setFont(font)
        self.ButtonXoaDT.setStyleSheet(" QPushButton {\n"
"        background-color: rgb(181, 62, 138);\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        border-radius: 10px;\n"
"        padding: 5px 10px;\n"
"        border: 2px solid #4682B4;\n"
"    }")
        self.ButtonXoaDT.setObjectName("ButtonXoaDT")
        self.ButtonTaiDT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonTaiDT.setGeometry(QtCore.QRect(620, 460, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonTaiDT.setFont(font)
        self.ButtonTaiDT.setStyleSheet(" QPushButton {\n"
"        background-color: rgb(181, 62, 138);\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        border-radius: 10px;\n"
"        padding: 5px 10px;\n"
"        border: 2px solid #4682B4;\n"
"    }")
        self.ButtonTaiDT.setObjectName("ButtonTaiDT")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 140, 901, 311))
        self.tableWidget_2.setStyleSheet("color: rgb(0, 0, 0); font: 87 10pt \"Segoe UI Black\";\n"
"QTableWidget {\n"
"    background-color: rgb(252, 255, 204); \n"
"    gridline-color: rgb(150, 150, 150); /* Màu đường kẻ ô */\n"
"}\n"
"QTableWidget::item {\n"
"    background-color: white; /* Màu nền ô mặc định */\n"
"    alternate-background-color: rgb(240, 240, 255); /* Màu nền xen kẽ xanh nhạt */\n"
"}\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(242, 247, 186))
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 0, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(232)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(120)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 901, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 143, 143))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 143, 143))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 143, 143))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 143, 143))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 143, 143))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 143, 143))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 143, 143))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 143, 143))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 143, 143))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: rosybrown; /* Màu nền nâu */\n"
"    color: white; /* Màu chữ trắng */\n"
"    font-size: 20px; /* Kích thước chữ */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    border-radius: 10px; /* Bo tròn góc 10px */\n"
"    padding: 5px; /* Khoảng cách giữa nội dung và viền */\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.ButtonQuaylaiDT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonQuaylaiDT.setGeometry(QtCore.QRect(30, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonQuaylaiDT.setFont(font)
        self.ButtonQuaylaiDT.setStyleSheet(" QPushButton {\n"
"        background-color: rgb(181, 62, 138);\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        border-radius: 10px;\n"
"        padding: 5px 10px;\n"
"        border: 2px solid #4682B4;\n"
"    }")
        self.ButtonQuaylaiDT.setObjectName("ButtonQuaylaiDT")
        self.ButtonLuuDT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonLuuDT.setGeometry(QtCore.QRect(150, 460, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonLuuDT.setFont(font)
        self.ButtonLuuDT.setStyleSheet(" QPushButton {\n"
"        background-color: rgb(181, 62, 138);\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        border-radius: 10px;\n"
"        padding: 5px 10px;\n"
"        border: 2px solid #4682B4;\n"
"    }")
        self.ButtonLuuDT.setObjectName("ButtonLuuDT")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 911, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(images_folder,"nen.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.ButtonXoaDT.raise_()
        self.ButtonTaiDT.raise_()
        self.tableWidget_2.raise_()
        self.label_2.raise_()
        self.ButtonQuaylaiDT.raise_()
        self.ButtonLuuDT.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ButtonXoaDT.setText(_translate("MainWindow", "Xoá"))
        self.ButtonTaiDT.setText(_translate("MainWindow", "Tải về"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tên phim"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Số vé đã bán"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Thành tiền"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ghi chú"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "BÁO CÁO DOANH THU"))
        self.ButtonQuaylaiDT.setText(_translate("MainWindow", "Quay lại"))
        self.ButtonLuuDT.setText(_translate("MainWindow", "Lưu"))
